spring.datasource.url=jdbc:postgresql://localhost:5432/vcilog_db
spring.datasource.username=workshop_user
spring.datasource.password=workshop_password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true